name: flutter_samples
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  hooks_riverpod: ^2.4.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flame: ^1.8.2
  equatable: ^2.0.5
  audioplayers: ^5.2.0
  freezed_annotation: ^2.4.1
  vector_math: ^2.1.4
  image: ^4.1.3
  http: ^1.1.0
  flat_3d_button: ^1.0.3
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

  flutter_lints: ^2.0.0
  freezed: ^2.4.5

flutter:
  assets:
    - assets/images/life_or_death/
    - assets/images/minesweeper/
    - assets/sounds/
  uses-material-design: true